// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBrEn5c_Mj1hp52D3viGhdiL76GmXR70',
    appId: '1:742215271085:web:8204599909c285a0333c24',
    messagingSenderId: '742215271085',
    projectId: 'clone-f9ca6',
    authDomain: 'clone-f9ca6.firebaseapp.com',
    storageBucket: 'clone-f9ca6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9X0HpH0wCMb2SVj21pq-_b8_S3kYJlh4',
    appId: '1:742215271085:android:eaafc5169eaf0e65333c24',
    messagingSenderId: '742215271085',
    projectId: 'clone-f9ca6',
    storageBucket: 'clone-f9ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYphJQ7cZR-I3gEGoIFYtmUKxCsdMyk5E',
    appId: '1:742215271085:ios:1d021e2d571bdc61333c24',
    messagingSenderId: '742215271085',
    projectId: 'clone-f9ca6',
    storageBucket: 'clone-f9ca6.appspot.com',
    iosBundleId: 'zeus.app.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYphJQ7cZR-I3gEGoIFYtmUKxCsdMyk5E',
    appId: '1:742215271085:ios:6371ec3f63443190333c24',
    messagingSenderId: '742215271085',
    projectId: 'clone-f9ca6',
    storageBucket: 'clone-f9ca6.appspot.com',
    iosBundleId: 'zeus.app.amazonClone.RunnerTests',
  );
}
